<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jokin" name="Test" tests="7" failures="1" timestamp="17 May 2018 12:00:08 GMT" time="30.1" errors="0">
  <testcase name="TestDome" time="5.875" classname="testcase.LongguoLoginTest"/>
  <testcase name="signOutTest" time="0.003" classname="testcase.CaseLoginTest"/>
  <testcase name="f" time="10.009" classname="testcase.CaseCompanyInfoTest">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="loginTest" time="8.412" classname="testcase.CaseLoginTest"/>
  <testcase name="f" time="10.025" classname="testcase.CaseCompanyInfoTest">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="choicePermissionTest" time="16.005" classname="testcase.CaseChoicePermissionTest"/>
  <testcase name="f" time="10.003" classname="testcase.CaseCompanyInfoTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at testcase.CaseCompanyInfoTest.f(CaseCompanyInfoTest.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
